tests/integration/targets/prepare_ovs_tests/tasks/main.yml
=> Add prepare_ovs_tests files

galaxy.yml
=> Update repo location in galaxy.yml

test-requirements.txt
=> Add pytest as a requirement

tests/integration/network-integration.cfg
=> Add missing ansible.cfg for integration tests

README.md, README.rst, galaxy.yml
documentation
```paste below
```
=> update ovs readme

plugins/modules/openvswitch_bridge.py, plugins/modules/openvswitch_db.py, plugins/modules/openvswitch_port.py
This commit adds the collection prefix to examples and adds a
version_added tag to the modules, mapping the collection release.
This commit removes ANSIBLE_METADA from the collection.
=> Adapt examples to collection format

README.md, docs/openvswitch.openvswitch.openvswitch_bridge.rst, docs/openvswitch.openvswitch.openvswitch_db.rst, docs/openvswitch.openvswitch.openvswitch_port.rst, plugins/modules/openvswitch_bridge.py, plugins/modules/openvswitch_db.py, plugins/modules/openvswitch_port.py
This PR This commit adds the documentation generated by collections_prep
with OVS Collection.
=> Add OVS modules DOC

README.rst, test-requirements.txt
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/442
=> Add coverage support to ovs 

bindep.txt
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/495
=> Add bindep.txt support

README.md
Minor change in example
README.md
=> Update collection version in example

README.md
=> added contributor link etc

README.md, docs/openvswitch.openvswitch.openvswitch_bridge_module.rst, docs/openvswitch.openvswitch.openvswitch_db_module.rst, docs/openvswitch.openvswitch.openvswitch_port_module.rst, meta/runtime.yml, plugins/modules/openvswitch_bridge.py, plugins/modules/openvswitch_db.py, plugins/modules/openvswitch_port.py, tests/unit/modules/network/ovs/test_openvswitch_bridge.py, tests/unit/modules/network/ovs/test_openvswitch_db.py, tests/unit/modules/network/ovs/test_openvswitch_port.py, tests/unit/modules/utils.py
- Updates for release readiness
=> Updates for release readiness

.yamllint, changelogs/CHANGELOG.rst, changelogs/changelog.yaml, changelogs/config.yaml, changelogs/fragments/41-add-change-log-1.0.0.yaml
*  Add changelog file for 1.0.0 release genereated
using https://github.com/ansible-community/antsibull-changelog
changelog
```paste below
```
=> Add changelog files

README.md
Now that our master branch has been renamed, we can also update
documentation.
=> Update references to main

bindep.txt, test-requirements.txt
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/604
=> Add missing dependencies for unit testing

README.md, changelogs/CHANGELOG.rst, changelogs/changelog.yaml, docs/openvswitch.openvswitch.openvswitch_bridge_module.rst, docs/openvswitch.openvswitch.openvswitch_db_module.rst, docs/openvswitch.openvswitch.openvswitch_port_module.rst, galaxy.yml
Fixes https://github.com/ansible-collections/openvswitch.openvswitch/issues/52
=> Prepare for 1.0.5 release

changelogs/fragments/fix_download_git.yaml, galaxy.yml
- Fixes #59 
- Bugfix Pull Request
=> Add version key to galaxy.yaml

README.md, docs/openvswitch.openvswitch.openvswitch_bond_module.rst, docs/openvswitch.openvswitch.openvswitch_bridge_module.rst, docs/openvswitch.openvswitch.openvswitch_db_module.rst, docs/openvswitch.openvswitch.openvswitch_port_module.rst
=> Update docs for for release

changelogs/CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/1-openvswitch_bond-new-module.yaml, changelogs/fragments/fix_download_git.yaml
=> Add changelog for 1.1.0

README.md, changelogs/fragments/fix_openvswitch_port.yaml, meta/runtime.yml, plugins/modules/openvswitch_bond.py, plugins/modules/openvswitch_bridge.py, plugins/modules/openvswitch_db.py, plugins/modules/openvswitch_port.py, tests/unit/modules/network/ovs/test_openvswitch_port.py
- Fixes #63 
- Feature Pull Request
openvswitch_port.py
=> Allow setting multiple properties on a port

changelogs/fragments/69-remove_tests_sanity_requirements.yml, tests/sanity/requirements.txt
https://github.com/ansible-collections/overview/issues/43
=> Remove tests/sanity/requirements.txt

CHANGELOG.rst, changelogs/changelog.yaml
Depends-On: https://github.com/ansible-collections/openvswitch.openvswitch/pull/73
To update the tagged version to 2.0.1, explaining the reason for the bump
openvswitch
```paste below
```
=> To update the tagged version to 2.0.1

changelogs/fragments/pylint_fixes.yaml, plugins/modules/openvswitch_bond.py, tests/integration/targets/openvswitch_bridge/tests/basic.yaml, tests/integration/targets/prepare_ovs_tests/tasks/main.yml, tests/unit/mock/loader.py
=> Fix pylint issue

CHANGELOG.rst, changelogs/.plugin-cache.yaml, changelogs/changelog.yaml, changelogs/fragments/69-remove_tests_sanity_requirements.yml, changelogs/fragments/fix_validate_modules.yaml, changelogs/fragments/fix_vlan_bridge_idempotency.yaml, changelogs/fragments/pylint_fixes.yaml
=> Prepare for v2.0.2

changelogs/fragments/openvswitch_db_read.yaml, docs/openvswitch.openvswitch.openvswitch_db_module.rst, plugins/modules/openvswitch_db.py, tests/unit/modules/network/ovs/test_openvswitch_db.py
Added code to perform read operation. Added test cases to test the read operation.
This patch helps in reading existing statistics and counters.
- Feature Pull Request
Module: openvswitch_db
feature: read operation
```paste below
```
=> Added code to perform read operation. Added testcases to test the read operation

CHANGELOG.rst, changelogs/.plugin-cache.yaml, changelogs/changelog.yaml, changelogs/fragments/84-ovs-modules-database-socket.yaml, changelogs/fragments/openvswitch_db_read.yaml
=> Prepare v2.1.0

.pre-commit-config.yaml, changelogs/config.yaml, changelogs/fragments/fix.yaml, docs/openvswitch.openvswitch.openvswitch_bond_module.rst, docs/openvswitch.openvswitch.openvswitch_bridge_module.rst, docs/openvswitch.openvswitch.openvswitch_db_module.rst, docs/openvswitch.openvswitch.openvswitch_port_module.rst, plugins/modules/openvswitch_bond.py, plugins/modules/openvswitch_bridge.py, plugins/modules/openvswitch_db.py, plugins/modules/openvswitch_port.py, test-requirements.txt, tests/integration/targets/prepare_ovs_tests/tasks/main.yml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1461
=> Fix CI issues

.github/workflows/test.yml, changelogs/fragments/gha.yaml, galaxy.yml, pyproject.toml, test-requirements.txt, tox.ini
Run sanity, units with GHA
Remove redundant netcommon dependency
Bump line length in black
=> Enable GHA for sanity and units

.github/workflows/tests.yml
It's a just simple fix for the test that is broken due to deprecation
- Bugfix Pull Request
CI (GitHub action)
=> Fix tests by excluding ansible-core>2.17
